language: java
install: true

jdk:
- openjdk10

addons:
  sonarcloud:
    organization: $SONAR_ORGANZATION # the key of the org you chose at step #3
    token: $SONAR_LOGIN_TOKEN

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/.gradle/caches
  - $HOME/.gradle/wrapper

script:
- ./gradlew build
- ./gradlew test
- ./gradlew sonarqube -Dsonar.projectKey=$SONAR_KEY -Dsonar.organization=$SONAR_ORGANZATION -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_LOGIN_TOKEN
